# Generated by Django 4.2.4 on 2023-08-20 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0002_alter_trips_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_day',
            field=models.DateField(default=models.DateField(default=datetime.date(2023, 8, 21)), null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_day',
            field=models.DateField(default=datetime.date(2023, 8, 21)),
        ),
    ]
